name: Build and Commit mdBook


on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.5
      with:
        rust-version: stable


    - name: Install mdBook
      run: cargo install mdbook

    - name: Build mdBook
      run: mdbook build

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git checkout -b gh-pages
        rm -rf src book.toml publish.ps1 README.md
        mv book booktemp
        mv booktemp/ . 
        rm -rf booktemp
        git add -A
        git commit -m "Updated Docs"
        git push origin gh-pages
